#include "pch.h"
#include "PrintModule.h"

#include <WebView2.h>
#include <shobjidl_core.h>
#include <wrl/client.h>
#include <wrl/event.h>

#include <string>

using namespace Microsoft::WRL;

namespace winrt::MoosiacRN::implementation {

void PrintModule::Initialize(
    winrt::Microsoft::ReactNative::ReactContext const &context) noexcept {
  m_context = context;
}

static std::wstring ChoosePdfPath(HWND owner, const std::string &jobName) {
  IFileSaveDialog *dialog = nullptr;
  if (FAILED(CoCreateInstance(CLSID_FileSaveDialog, nullptr,
                              CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&dialog))) ||
      !dialog) {
    return {};
  }

  COMDLG_FILTERSPEC filters[] = {{L"PDF document", L"*.pdf"}};
  dialog->SetFileTypes(ARRAYSIZE(filters), filters);
  dialog->SetDefaultExtension(L"pdf");
  dialog->SetFileName(winrt::to_hstring(jobName.empty() ? "Score" : jobName).c_str());
  DWORD options = 0;
  dialog->GetOptions(&options);
  dialog->SetOptions(options | FOS_FORCEFILESYSTEM | FOS_OVERWRITEPROMPT);

  const HRESULT shown = dialog->Show(owner);
  if (FAILED(shown)) {
    dialog->Release();
    return {};
  }
  IShellItem *item = nullptr;
  const HRESULT result = dialog->GetResult(&item);
  dialog->Release();
  if (FAILED(result) || !item) return {};

  PWSTR rawPath = nullptr;
  const HRESULT pathResult = item->GetDisplayName(SIGDN_FILESYSPATH, &rawPath);
  item->Release();
  if (FAILED(pathResult) || !rawPath) return {};
  std::wstring path(rawPath);
  CoTaskMemFree(rawPath);
  return path;
}

void PrintModule::printPages(
    std::string jobName, React::JSValueArray pages,
    React::ReactPromise<bool> result) noexcept {
  m_context.UIDispatcher().Post(
      [context = m_context, jobName = std::move(jobName), pages = std::move(pages),
       result = std::move(result)]() mutable {
        std::string html =
            "<!doctype html><html><head><meta charset=\"utf-8\"><style>"
            "@page{margin:0}html,body{margin:0;padding:0;background:white}"
            ".page{break-after:page;break-inside:avoid;display:block}"
            ".page:last-child{break-after:auto}svg{display:block}"
            "</style></head><body>";
        size_t validPages = 0;
        for (const auto &page : pages) {
          if (page.Type() != React::JSValueType::Object) continue;
          const auto &object = page.AsObject();
          const auto svg = object.find("svg");
          if (svg == object.end() || svg->second.Type() != React::JSValueType::String) continue;
          // This is trusted SVG generated by the app's renderer. Keep the
          // markup intact: escaping it would turn the page into plain text.
          html += "<div class=\"page\">" + svg->second.AsString() + "</div>";
          validPages++;
        }
        html += "</body></html>";
        if (validPages == 0) {
          result.Reject(React::ReactError{"NO_PAGES", "There was nothing to print."});
          return;
        }

        HWND owner = reinterpret_cast<HWND>(
            winrt::Microsoft::ReactNative::ReactCoreInjection::GetTopLevelWindowId(
                context.Properties().Handle()));
        const std::wstring outputPath = ChoosePdfPath(owner, jobName);
        if (outputPath.empty()) {
          result.Resolve(false);
          return;
        }

        auto htmlWide = winrt::to_hstring(html);
        CreateCoreWebView2EnvironmentWithOptions(
            nullptr, nullptr, nullptr,
            Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
                [htmlWide, outputPath, result = std::move(result)](
                    HRESULT environmentResult, ICoreWebView2Environment *environment) mutable -> HRESULT {
                  if (FAILED(environmentResult) || !environment) {
                    result.Reject(React::ReactError{"WEBVIEW_ERROR", "WebView2 is not available."});
                    return S_OK;
                  }
                  environment->CreateCoreWebView2Controller(
                      HWND_MESSAGE,
                      Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                          [htmlWide, outputPath, result = std::move(result)](
                              HRESULT controllerResult, ICoreWebView2Controller *controller) mutable -> HRESULT {
                            if (FAILED(controllerResult) || !controller) {
                              result.Reject(React::ReactError{"WEBVIEW_ERROR", "Could not create print surface."});
                              return S_OK;
                            }
                            // Held, not borrowed: WebView2 releases its reference when this
                            // handler returns, and the print surface must outlive the navigation.
                            ComPtr<ICoreWebView2Controller> surface(controller);
                            ComPtr<ICoreWebView2> webview;
                            controller->get_CoreWebView2(&webview);
                            if (!webview) {
                              controller->Close();
                              result.Reject(React::ReactError{"WEBVIEW_ERROR", "Could not create print surface."});
                              return S_OK;
                            }
                            ::EventRegistrationToken token{};
                            webview->add_NavigationCompleted(
                                Callback<ICoreWebView2NavigationCompletedEventHandler>(
                                    [webview, surface, outputPath, result = std::move(result)](
                                        ICoreWebView2 *, ICoreWebView2NavigationCompletedEventArgs *) mutable -> HRESULT {
                                      ComPtr<ICoreWebView2_7> printable;
                                      webview.As(&printable);
                                      if (!printable) {
                                        surface->Close();
                                        result.Reject(React::ReactError{"WEBVIEW_ERROR", "This WebView2 runtime cannot print to PDF."});
                                        return S_OK;
                                      }
                                      printable->PrintToPdf(
                                          outputPath.c_str(), nullptr,
                                          Callback<ICoreWebView2PrintToPdfCompletedHandler>(
                                              [surface, result = std::move(result)](HRESULT printResult, BOOL success) mutable -> HRESULT {
                                                surface->Close();
                                                if (SUCCEEDED(printResult) && success) result.Resolve(true);
                                                else result.Reject(React::ReactError{"PDF_ERROR", "Failed to create the PDF."});
                                                return S_OK;
                                              }).Get());
                                      return S_OK;
                                    }).Get(), &token);
                            webview->NavigateToString(htmlWide.c_str());
                            return S_OK;
                          }).Get());
                  return S_OK;
                }).Get());
      });
}

} // namespace winrt::MoosiacRN::implementation
